server:
  port: 37060
spring:
  config:
    import:
      - optional:configserver:http://192.168.0.31:8888
  kafka:
    bootstrap-servers: 192.168.0.31:9092
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:38761/eureka